---
- name: Create Plex config directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user_name }}/app/plex/config"
    state: directory
    owner: "{{ ansible_user_name }}"
    group: "{{ ansible_user_name }}"
    mode: '0755'

- name: Create media directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user_name }}"
    group: "{{ ansible_user_name }}"
    mode: '0755'
  loop:
    - "/home/{{ ansible_user_name }}/media/tvshows"
    - "/home/{{ ansible_user_name }}/media/movies"
