---
- name Create NPM directories
  ansible.builtin.file:
    path: "/home/floki/docker/npm/{{ item }}"
    state: directory
    owner: floki
    group: floki
    mode: '0755'
  loop:
    - data
    - letsencrypt

- name: Add NPM service to docker-compose
  ansible.builtin.blockinfile:
    path: /home/floki/docker/docker/docker-compose.yml
    block: |
      npm:
        image: 'jc21/nginx-proxy-manager:latest'
        container_name: npm
        restart: unless-stopped
        ports: 
          - '80:80'
          - '81:81'
          - '443:443'
        volumes:
          - ./npm/data:/data
          - ./npm/letsencrypt:/etc/letsencrypt
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR NPM"